- name: show retrun value of command module
  hosts: webservers
  tasks: 
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - name: print boot title
      debug: msg="the title of the book is {{ansible_local.example.book.title}}"
